Uni\AdminBundle\Entity\ProjectPhoto:
    type: entity
    table: ProjectPhoto
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
            length: '300'
            nullable: true
        file:
            type: string
            length: '300'
            nullable: true
    manyToOne:
        project:
            targetEntity: Project
            inversedBy: photos
    lifecycleCallbacks: {  }