Uni\AdminBundle\Entity\Project:
    type: entity
    table: Project
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '200'
        content:
            type: text
            nullable: true
        progress:
            type: integer
        published:
            type: boolean
            options:
                default: false
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    oneToMany:
        photos:
            targetEntity: ProjectPhoto
            cascade: [persist]
            mappedBy: project
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }