# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        less:
            node: %node%
            node_paths: [%node_modules%]
            apply_to: "\.less$"
        cssrewrite: ~
    assets:
        font-awesome-otf:
            inputs: '%kernel.root_dir%/Resources/fonts/FontAwesome.otf'
            output: fonts/FontAwesome.otf
        font-awesome-eot:
            inputs: '%kernel.root_dir%/Resources/fonts/fontawesome-webfont.eot'
            output: fonts/fontawesome-webfont.eot
        font-awesome-svg:
            inputs: '%kernel.root_dir%/Resources/fonts/fontawesome-webfont.svg'
            output: fonts/fontawesome-webfont.svg
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/Resources/fonts/fontawesome-webfont.ttf'
            output: fonts/fontawesome-webfont.ttf
        font-awesome-woff:
            inputs: '%kernel.root_dir%/Resources/fonts/fontawesome-webfont.woff'
            output: fonts/fontawesome-webfont.woff
        font-awesome-woff2:
            inputs: '%kernel.root_dir%/Resources/fonts/fontawesome-webfont.woff2'
            output: fonts/fontawesome-webfont.woff2
        font_awesome_css:
            inputs:
                - %kernel.root_dir%/Resources/css/font-awesome.min.css
            output: css/font-awesome.min.css
        jquery_js:
            inputs:
                - %kernel.root_dir%/Resources/js/jquery.min.js
            output: js/jquery.min.js
        jqueryui_js:
            inputs:
                - %kernel.root_dir%/Resources/js/jquery-ui.min.js
            output: js/jquery-ui.min.js
        jqueryui_css:
            inputs:
                - %kernel.root_dir%/Resources/css/jquery-ui.min.css
            output: css/jquery-ui.min.css
        fileinput_js:
            inputs:
                - %kernel.root_dir%/Resources/js/fileinput.min.js
            output: js/fileinput.min.js
        fileinput_css:
            inputs:
                - %kernel.root_dir%/Resources/css/fileinput.min.css
            output: css/fileinput.min.css
        analytics_js:
            inputs:
                - %kernel.root_dir%/Resources/js/analytics.js
            output: js/analytics.js
        uniAdmin_css:
            inputs:
                - %kernel.root_dir%/Resources/less/switch/build.less
                - %kernel.root_dir%/Resources/less/uniAdmin/build.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - less
                - cssrewrite
            output: css/uniAdmin.css
        uniPage_css:
            inputs:
                - %kernel.root_dir%/Resources/less/uniPage/build.less
            filters:
                - less
                - cssrewrite
            output: css/uniPage.css
        uniAdmin_js:
            inputs:
                - %kernel.root_dir%/Resources/js/transition.js
                - %kernel.root_dir%/Resources/js/alert.js
                - %kernel.root_dir%/Resources/js/button.js
                - %kernel.root_dir%/Resources/js/carousel.js
                - %kernel.root_dir%/Resources/js/collapse.js
                - %kernel.root_dir%/Resources/js/dropdown.js
                - %kernel.root_dir%/Resources/js/modal.js
                - %kernel.root_dir%/Resources/js/tooltip.js
                - %kernel.root_dir%/Resources/js/popover.js
                - %kernel.root_dir%/Resources/js/scrollspy.js
                - %kernel.root_dir%/Resources/js/tab.js
                - %kernel.root_dir%/Resources/js/affix.js
                - %kernel.root_dir%/Resources/js/bootstrap-switch.js
                - %kernel.root_dir%/Resources/js/sb-admin-2.js
                - %kernel.root_dir%/Resources/js/metisMenu.js
                - %kernel.root_dir%/Resources/js/uniAdmin-main.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            output: js/uniAdmin.js
        uniPage_js:
            inputs:
                - %kernel.root_dir%/Resources/js/transition.js
                - %kernel.root_dir%/Resources/js/alert.js
                - %kernel.root_dir%/Resources/js/button.js
                - %kernel.root_dir%/Resources/js/carousel.js
                - %kernel.root_dir%/Resources/js/collapse.js
                - %kernel.root_dir%/Resources/js/dropdown.js
                - %kernel.root_dir%/Resources/js/modal.js
                - %kernel.root_dir%/Resources/js/tooltip.js
                - %kernel.root_dir%/Resources/js/popover.js
                - %kernel.root_dir%/Resources/js/scrollspy.js
                - %kernel.root_dir%/Resources/js/tab.js
                - %kernel.root_dir%/Resources/js/affix.js
                - %kernel.root_dir%/Resources/js/clean-blog.js
                - %kernel.root_dir%/Resources/js/uniPage-main.js
            output: js/uniPage.js

