imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: images.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: [es] }
    default_locale: es
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    #validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    validation:      { enabled: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  es
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - :Form:form_div_layout.html.twig

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
    assets:
        font-awesome-otf:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/FontAwesome.otf'
            output: fonts/FontAwesome.otf
        font-awesome-eot:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.eot'
            output: fonts/fontawesome-webfont.eot
        font-awesome-svg:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.svg'
            output: fonts/fontawesome-webfont.svg
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf'
            output: fonts/fontawesome-webfont.ttf
        font-awesome-woff:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff'
            output: fonts/fontawesome-webfont.woff
        font-awesome-woff2:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff2'
            output: fonts/fontawesome-webfont.woff2
        font_awesome_css:
            inputs:
                - %kernel.root_dir%/../vendor/components/font-awesome/css/font-awesome.min.css
            output: css/font-awesome.min.css
        jquery_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
            output: js/jquery.min.js
        jqueryui_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/jquery-ui.min.js
            output: js/jquery-ui.min.js
        fileinput_js:
            inputs:
                - %kernel.root_dir%/../vendor/kartik-v/bootstrap-fileinput/js/fileinput.min.js
            output: js/fileinput.min.js
        fileinput_locale_es_js:
            inputs:
                - %kernel.root_dir%/../vendor/kartik-v/bootstrap-fileinput/js/fileinput_locale_es.js
            output: js/fileinput_locale_es.js
        jqueryui_css:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/themes/base/jquery-ui.min.css
            output: css/jquery-ui.min.css
        fileinput_css:
            inputs:
                - %kernel.root_dir%/../vendor/kartik-v/bootstrap-fileinput/css/fileinput.min.css
            output: css/fileinput.min.css
        uniAdmin_css:
            inputs:
                - %kernel.root_dir%/../vendor/components/bootstrap-switch/src/less/bootstrap3/build.less
                - %kernel.root_dir%/Resources/less/uniAdmin.less
                - %kernel.root_dir%/../bower_components/startbootstrap-sb-admin-2/less/sb-admin-2.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - less
                - cssrewrite
            output: css/uniAdmin.css
        uniPage_css:
            inputs:
                - %kernel.root_dir%/Resources/less/uniPage.less
                - %kernel.root_dir%/Resources/less/clean-blog/clean-blog.less
                #- %kernel.root_dir%/../git_components/startbootstrap-clean-blog/less/clean-blog.less
            filters:
                - less
                - cssrewrite
            output: css/uniPage.css
        uniAdmin_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/components/bootstrap-switch/dist/js/bootstrap-switch.js
                - %kernel.root_dir%/../bower_components/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js
                - %kernel.root_dir%/../bower_components/metisMenu/src/metisMenu.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            output: js/uniAdmin.js
        uniPage_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/components/bootstrap/js/affix.js
                - %kernel.root_dir%/../bower_components/metisMenu/src/metisMenu.js
                - %kernel.root_dir%/../git_components/startbootstrap-clean-blog/js/clean-blog.js
            output: js/uniPage.js

braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/components/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
    less_filter: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    icon_prefix: fa
    fontawesome_dir: 
    auto_configure:
        assetic: false
        twig: false
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: %kernel.root_dir%/Resources/less/variables.less
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: es_ES

    # Only used if you activated the Uploadable extension
    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:       %kernel.root_dir%/../web/uploads

        # Mime type guesser class: Optional. By default, we provide an adapter for the one present in the HttpFoundation component of Symfony
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter

        # Default file info class implementing FileInfoInterface: Optional. By default we provide a class which is prepared to receive an UploadedFile instance.
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            timestampable: true
            sortable: true
            softdeleteable: true

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

fos_user:
    # tipo de ORM/ODB que utilizas (también puede ser 'mongodb', 'couchdb' y 'propel')
    db_driver:     orm
    # el nombre de tu firewall
    firewall_name: main
    # el namespace de tu clase 'User' específica
    user_class:    Uni\UserBundle\Entity\User
    #change_password:
    #    form:
    #        type: sig_fichasocial_change_password
    #        name: sig_fichasocial_change_password
    #use_listener: false

knp_paginator:
    page_range: 3                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        #pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        pagination: :Pagination:pagination.html.twig

stfalcon_tinymce:
    selector: ".tinymce"
    # Get current language from the parameters.ini
    language: %locale%
    # Custom buttons
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        advanced:
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
            plugins: ["bbcode, code, link, preview"]
            menubar: false
            toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"