fos_user:
    # tipo de ORM/ODB que utilizas (también puede ser 'mongodb', 'couchdb' y 'propel')
    db_driver:     orm
    # el nombre de tu firewall
    firewall_name: main
    # el namespace de tu clase 'User' específica
    user_class:    Uni\UserBundle\Entity\User
    #change_password:
    #    form:
    #        type: sig_fichasocial_change_password
    #        name: sig_fichasocial_change_password
    #use_listener: false

