# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_denied_url:    ~
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
#        in_memory:
#            memory:
#                users:
#                    ivan:  { password: ivan, roles: 'ROLE_ADMIN' }
#                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
#                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#            anonymous: ~

#        login_firewall:
#            pattern:   ^/login$
#            anonymous: ~

        main:
            pattern:   ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            form_login:
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /admin
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                failure_path: /login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, role: ROLE_USER }
        - { path: ^/register, role: ROLE_USER }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin$, roles: ROLE_USER }
        # - { path: ^/, roles: ROLE_ADMIN }
        # Include the following line to also secure the /admin path itself
