<?php

namespace Proxies\__CG__\Uni\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Member extends \Uni\AdminBundle\Entity\Member implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'id', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'firstname', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'lastname', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'email', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'phonenumber', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'birthdate', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'admissiondate', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'active', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'path', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'file', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'createdAt', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'updatedAt', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'deletedAt', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'role', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'courses', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'previous_roles');
        }

        return array('__isInitialized__', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'id', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'firstname', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'lastname', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'email', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'phonenumber', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'birthdate', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'admissiondate', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'active', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'path', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'file', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'createdAt', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'updatedAt', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'deletedAt', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'role', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'courses', '' . "\0" . 'Uni\\AdminBundle\\Entity\\Member' . "\0" . 'previous_roles');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Member $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', array($lastname));

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', array());

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhonenumber($phonenumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhonenumber', array($phonenumber));

        return parent::setPhonenumber($phonenumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhonenumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhonenumber', array());

        return parent::getPhonenumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthdate($birthdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthdate', array($birthdate));

        return parent::setBirthdate($birthdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthdate', array());

        return parent::getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmissiondate($admissiondate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmissiondate', array($admissiondate));

        return parent::setAdmissiondate($admissiondate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmissiondate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmissiondate', array());

        return parent::getAdmissiondate();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', array($path));

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', array());

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', array($deletedAt));

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', array());

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole(\Uni\AdminBundle\Entity\MemberRole $role = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', array($role));

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array());

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function addCourse(\Uni\AdminBundle\Entity\MemberCourse $courses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCourse', array($courses));

        return parent::addCourse($courses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCourse(\Uni\AdminBundle\Entity\MemberCourse $courses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCourse', array($courses));

        return parent::removeCourse($courses);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourses', array());

        return parent::getCourses();
    }

    /**
     * {@inheritDoc}
     */
    public function addPreviousRole(\Uni\AdminBundle\Entity\MemberRole $previousRoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreviousRole', array($previousRoles));

        return parent::addPreviousRole($previousRoles);
    }

    /**
     * {@inheritDoc}
     */
    public function removePreviousRole(\Uni\AdminBundle\Entity\MemberRole $previousRoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePreviousRole', array($previousRoles));

        return parent::removePreviousRole($previousRoles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousRoles', array());

        return parent::getPreviousRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

}
