uni_admin_frontpagephoto:
    resource: "@UniAdminBundle/Resources/config/routing/frontpagephoto.yml"
    prefix:   /frontpagephoto

uni_admin_frontpage:
    resource: "@UniAdminBundle/Resources/config/routing/frontpage.yml"
    prefix:   /frontpage

uni_admin_history:
    resource: "@UniAdminBundle/Resources/config/routing/history.yml"
    prefix:   /history

uni_admin_reportphoto:
    resource: "@UniAdminBundle/Resources/config/routing/reportphoto.yml"
    prefix:   /reportphoto

uni_admin_report:
    resource: "@UniAdminBundle/Resources/config/routing/report.yml"
    prefix:   /report

uni_admin_role:
    resource: "@UniAdminBundle/Resources/config/routing/role.yml"
    prefix:   /role

uni_admin_member:
    resource: "@UniAdminBundle/Resources/config/routing/member.yml"
    prefix:   /member

uni_admin_noticephoto:
    resource: "@UniAdminBundle/Resources/config/routing/noticephoto.yml"
    prefix:   /noticephoto

uni_admin_notice:
    resource: "@UniAdminBundle/Resources/config/routing/notice.yml"
    prefix:   /notice

uni_admin_user:
    resource: "@UniAdminBundle/Resources/config/routing/user.yml"
    prefix:   /user

uni_admin:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/frontpage
        permanent: true