document:
    path:     /
    defaults: { _controller: "UniAdminBundle:Document:index" }
    methods: [GET]

document_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Document:show" }

document_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Document:new" }

document_create:
    path:     /create
    defaults: { _controller: "UniAdminBundle:Document:create" }
    methods: [POST]

document_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Document:edit" }

document_update:
    path:     /{id}/update
    defaults: { _controller: "UniAdminBundle:Document:update" }
    methods: [POST|PUT]

document_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Document:delete" }
    methods: [POST|DELETE]
