frontpagephoto:
    path:     /
    defaults: { _controller: "UniAdminBundle:FrontpagePhoto:index" }
    methods: [GET]

frontpagephoto_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:FrontpagePhoto:show" }

frontpagephoto_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:FrontpagePhoto:new" }

frontpagephoto_create:
    path:     /create
    defaults: { _controller: "UniAdminBundle:FrontpagePhoto:create" }
    methods: [POST]

frontpagephoto_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:FrontpagePhoto:edit" }

frontpagephoto_update:
    path:     /{id}/update
    defaults: { _controller: "UniAdminBundle:FrontpagePhoto:update" }
    methods: [POST|PUT]

frontpagephoto_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:FrontpagePhoto:delete" }
    methods: [POST|DELETE]
