role:
    path:     /
    defaults: { _controller: "UniAdminBundle:Role:index" }
    methods: [GET]

role_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Role:show" }

role_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Role:new" }

role_create:
    path:     /create
    defaults: { _controller: "UniAdminBundle:Role:create" }
    methods: [POST]

role_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Role:edit" }

role_update:
    path:     /{id}/update
    defaults: { _controller: "UniAdminBundle:Role:update" }
    methods: [POST|PUT]

role_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Role:delete" }
    methods: [POST|DELETE]
